print("Day 1: ", solveCaptcha(day1Input))
print("Day 2: ", checksum(day2Input))
print("Day 3: ", getDistance(from: day3Input))
print("Day 4: ", getValidPassphraseCount(day4Input))
print("Day 5: ", solveJumpMaze(day5Input))
print("Day 6: ", reallocateMemory(day6Input))
