print("Day 1:", solveCaptcha(day1Input))
print("Day 2:", checksum(day2Input))
print("Day 3:", getDistance(from: day3Input))
print("Day 4:", getValidPassphraseCount(day4Input))
print("Day 5:", solveJumpMaze(day5Input))
print("Day 6:", reallocateMemory(day6Input))
print("Day 7:", findRootProgram(day7Input))
print("Day 8:", largestRegisterValue(afterExecuting: day8Input))
print("Day 9:", calculateScore(day9Input))
print("Day 10:", knotHash(day10Input))
print("Day 11:", getHexDistance(day11Input))
print("Day 12:", findRootGroupCount(day12Input))
print("Day 13:", findSeverity(day13Input))
print("Day 14:", countSquaresUsed(day14Input))
print("Day 15:", generatorBattle(seeds: day15Input))
print("Day 16:", getFinalPositions(day16Input))
print("Day 17:", spinlock(stepping: day17Input))
if #available(OSX 10.12, *) {
    print("Day 18:", findFrequency(day18Input))
}
